name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Verification
        run: ./gradlew :app:assemble
