name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build Verification
        run: ./gradlew :app:build

      - name: Detekt Verification
        run: ./gradlew detekt

      - name: Detekt auto correct
        run: ./gradlew detekt --auto-correct

      - name: Commit updated file
        run: |
          git add ."
          git commit -m "Detekt auto correct"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
            sarif_file: build/reports/detekt/detekt.sarif
