name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build Verification
        run: ./gradlew :app:build

      - name: Detekt Verification
        run: ./gradlew detekt

      - name: Danger # And Danger action
        uses: docker://ghcr.io/danger/danger-kotlin:1.0.0
        with:
          args: --dangerfile config/danger/config.df.kts # Note I have config located like this
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Extracted automatically


